### ISSUE TITLE
Posição errada da tag `script`

### ISSUE THREAD

**Issue by lucasferreira** [LeonardoCechellaVelho/atv-sw-chat#1]
Opa,

Apesar de "funcionar" não é correto por a tag script neste local

https://github.com/LeonardoCechellaVelho/atv-sw-chat/blob/8504c51d8b6ab94d5ac761a8212e0e3156446d75/chat.html#L120-L125

O recomendado é que tudo que é relacionado a JavaScript, fique dentro do BODY ou do HEAD.

No seu caso eu recomendo que fique no final do BODY, antes da tag `</body>` _(e não fora como tu fez)_.

Beleza?

**Comment by LeonardoCechellaVelho** [comment]
Opa, acabei vendo só hoje, belo trabalho, não esperava que fosse comentar em cada projeto kkkk, mas agradeço o aviso, em projetos futuros levarei isso em consideração, vou alterar nesse também, obrigado!
