### ISSUE TITLE
Reorganização e uso do campo chat

### ISSUE THREAD

**Issue by lucasferreira** [LeonardoCechellaVelho/atv-sw-chat#2]
Em uma análise mais "aprofundada" acho que podemos melhorar o conceito aplicado nessa função aqui:

https://github.com/LeonardoCechellaVelho/atv-sw-chat/blob/8504c51d8b6ab94d5ac761a8212e0e3156446d75/chat.html#L134-L137

Porque eu notei que dentro da função `enviaMsg` tais novamente resgatando o campo `#chat` para limpar o valor dele. Porém no momento que tu resolve passar a nova mensagem como um argumento na hora de chamar a função `enviaMsg` fica implícito que esta última função não deveria lidar diretamente com o campo `#chat` (quem faz isso é a função `addText`).

Eu recomendaria duas coisas:

1 - Remover a linha 157 (`document.getElementById("chat").value = "";`)
2 - Resolver esta questão dentro da função `addText`, mais ou menos assim:

```js
function addText() {
  var chat = document.getElementById("chat");
  
  var texto = chat.value; 
  enviaMsg(texto);

  // limpando o campo
  chat.value = "";
} 
```

Beleza?

**Comment by LeonardoCechellaVelho** [comment]
Opa, vou fazer isso para dar uma ajeitada no código, valeu pela dica!!
